name: CI/CD for FastAPI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app

jobs:
  lint-black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "requirements.txt"

      - name: Install Black
        run: |
          uv pip install --system black
          if [ -f requirements.txt ]; then uv pip install --system -r requirements.txt; fi

      - name: Lint with Black
        run: black --check .

  lint-flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "requirements.txt"

      - name: Install Flake8
        run: |
          uv pip install --system flake8
          if [ -f requirements.txt ]; then uv pip install --system -r requirements.txt; fi

      - name: Lint with Flake8
        run: flake8 .

  test:
    needs: [lint-black, lint-flake8]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "requirements.txt"

      - name: Install Pytest
        run: |
          uv pip install --system pytest
          if [ -f requirements.txt ]; then uv pip install --system -r requirements.txt; fi

      - name: Run tests
        run: pytest

  build-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 7000
          key: ${{ secrets.SSH_KEY }}
          sync: true
          script_stop: true
          script: |
            cd /home/topinambur02/test-ci-cd
            
            git pull origin main
            
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            
            export IMAGE_NAME="${{ env.IMAGE_NAME }}:latest"
            docker compose pull
            
            docker compose up -d --remove-orphans